# Generated by Django 5.2.5 on 2025-08-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail_url",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="video",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
