# Generated by Django 4.2.23 on 2025-08-24 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0002_video_thumbnail_url_video_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likereaction',
            unique_together={('student', 'video')},
        ),
    ]
