# Generated by Django 5.2.5 on 2025-08-24 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_video_thumbnail_url_video_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="likereaction",
            unique_together={("student", "video")},
        ),
    ]
