# Generated by Django 5.2.5 on 2025-08-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_likereaction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
