# Generated by Django 5.2.5 on 2025-08-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.FileField(upload_to='video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
