<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-08-28 16:16
=======
# Generated by Django 5.2.5 on 2025-08-28 15:40
>>>>>>> f32b9ff68b72768e79e4547749f61cddee64eff5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_thumbnail_url_alter_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
