# Generated by Django 5.2.5 on 2025-08-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
