# Generated by Django 5.2.5 on 2025-08-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('general', 'General Inquiry'), ('tech', 'Technical Support'), ('billing', 'Billing & Payments'), ('enroll', 'Course Enrollment'), ('teacher', 'Teacher Application'), ('feedback', 'Feedback & Suggestions'), ('partner', 'Collaboration / Partnership'), ('other', 'Other')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
