# Generated by Django 5.2.5 on 2025-08-23 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=25, unique=True)),
                ("description", models.TextField()),
                ("price", models.FloatField(default=0)),
                ("discount", models.FloatField(default=0)),
                ("currency", models.CharField(default="EGP", max_length=3)),
                ("is_paid", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("category", models.CharField(max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("rating", models.FloatField(default=0)),
                ("thumbnail", models.URLField()),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
