# Generated by Django 5.2.5 on 2025-08-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
