# Generated by Django 5.2.5 on 2025-08-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.FloatField(default=0),
        ),
    ]
