# Generated by Django 5.2.5 on 2025-08-25 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('videos', '0004_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='video',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='videos.video'),
        ),
    ]
