# Generated by Django 5.2.5 on 2025-08-26 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_video'),
        ('videos', '0004_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='videos.video'),
        ),
    ]
