# Generated by Django 5.2.5 on 2025-08-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.FileField(upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail_url',
            field=models.FileField(upload_to='book_covers/'),
        ),
    ]
