# Generated by Django 4.2.23 on 2025-08-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.FileField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
