# Generated by Django 5.2.5 on 2025-09-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.FileField(blank=True, default='profile_images/avatar.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
