# Generated by Django 5.2.5 on 2025-08-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_school_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school_year',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
