# Generated by Django 5.2.5 on 2025-08-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_school_year_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="student", max_length=10),
        ),
    ]
